// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsEmoY8LAm_TcugZSb_sT_gur8ERF-XNk',
    appId: '1:704911555426:web:2c8ab30a927613e72c0a3b',
    messagingSenderId: '704911555426',
    projectId: 'kishore-electrical',
    authDomain: 'kishore-electrical.firebaseapp.com',
    storageBucket: 'kishore-electrical.appspot.com',
    measurementId: 'G-ZZFPM0FLJY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyyH194BnlRlA6jSVI502S994BC0UWRRE',
    appId: '1:704911555426:android:cdf5f3c39ca1cc9a2c0a3b',
    messagingSenderId: '704911555426',
    projectId: 'kishore-electrical',
    storageBucket: 'kishore-electrical.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRmK_BLB_Iq0owfgoOldwT9yEr7VRT5Q4',
    appId: '1:704911555426:ios:66d46eca4de8b66f2c0a3b',
    messagingSenderId: '704911555426',
    projectId: 'kishore-electrical',
    storageBucket: 'kishore-electrical.appspot.com',
    iosClientId: '704911555426-ildnr40od38rp8n0tvn5a0mvu0eb9okv.apps.googleusercontent.com',
    iosBundleId: 'com.hdmdmi.kem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRmK_BLB_Iq0owfgoOldwT9yEr7VRT5Q4',
    appId: '1:704911555426:ios:66d46eca4de8b66f2c0a3b',
    messagingSenderId: '704911555426',
    projectId: 'kishore-electrical',
    storageBucket: 'kishore-electrical.appspot.com',
    iosClientId: '704911555426-ildnr40od38rp8n0tvn5a0mvu0eb9okv.apps.googleusercontent.com',
    iosBundleId: 'com.hdmdmi.kem',
  );
}
